### ISSUE TITLE
Incorrect data saving for 2nd round

### ISSUE THREAD

**Issue by Gi0vanniM** [Remynijsten/scrumbers-client#15]
**Reproduceren:**
Begin een sessie, submit in de 1ste ronde een kaart en een chatbericht.
En dan in de 2de ronde submit weer een kaart en chatbericht.

**Verwachte gedrag:**
De gekozen kaart en chatbericht wordt correct opgeslagen in de database

**Geconstateerde gedrag:**
Er wordt '0' en '' (lege string) opgeslagen voor de kaart en chatbericht.

**Release:** 0.4.0

**De melder:**
Giovanni Mierop

**Datum:**
21-11-2021

**Comment by RickLugtigheid** [comment]
Fixed Incorrect data saving for 2nd round

**Comment by RickLugtigheid** [comment]
Fixed Incorrect data saving for 2nd round
