### ISSUE TITLE
Na het spel komt de history niet in beeld.

### ISSUE THREAD

**Issue by RickSnijders** [Remynijsten/scrumbers-client#49]
Reproduceren:
Maak een sessie aan
speel de sessie af

Verwachte gedrag:
history komt in beeld

Geconstateerde gedrag:
history komt niet in beeld

Release:
0.0.7

De melder: 
Rick Snijders

Datum:
11-1-2022

**Comment by RickLugtigheid** [comment]
Fixed issue in this pull request: [https://github.com/Remynijsten/scrumbers-server/pull/44](https://github.com/Remynijsten/scrumbers-server/pull/44)
