### ISSUE TITLE
Oneindig lange timeout als de timeout lengte op een negatief getal staat

### ISSUE THREAD

**Issue by RickLugtigheid** [Remynijsten/scrumbers-client#50]
### Reproduceren:
- Maak een sessie aan en zet in de sessie settings de koffie timeout naar een negatief getal (bvb: -10)
- Start de sessie en kies gelijk de Koffie kaart
- De timer word steeds een hoger min getal, omdat: `-1 - 1 = -2`

### Verwachte gedrag:
- Ik krijg een error dat ik geen negatief nummer mag invullen en de sessie word niet aangemaakt

### Geconstateerde gedrag:
- Er word een sessie gecreëerd en ik kan een oneindige koffie timeout activeren als de koffie kaart gekozen word

### Release:
- V0.4.0

### De melder: 
- Rick Lugtigheid

### Datum:
- 12-01-2022

**Comment by Remynijsten** [comment]
Is gefixt. Koffie timeout accepteert geen negatieve getallen of 0 meer
