### ISSUE TITLE
Checkbox van cardtemplate markeert alle andere ook als checked

### ISSUE THREAD

**Issue by Remynijsten** [Remynijsten/scrumbers-client#70]
Reproduceren:
Ga naar de create-room pagina en klik een template aan rechts

Verwachte gedrag:
Enkel degene die je aanklikt krijgt een vinkje

Geconstateerde gedrag:
Alle andere krijgen ook een blauwe 'checked' markering

Release:
v0.8.0

De melder: 
Remy Nijsten

Datum:
27-01-2022

**Comment by RickLugtigheid** [comment]
Gefikst in pull request: https://github.com/Remynijsten/scrumbers-client/pull/71
