### ISSUE TITLE
Side menu blijft soms open wanneer je van route veranderd

### ISSUE THREAD

**Issue by Remynijsten** [Remynijsten/scrumbers-client#72]
**Reproduceren:**
Maak een nieuwe sessie aan en open het sidemenu waar de attachment/checklists staan
Ga naar de vorige pagina in je browser

**Verwachte gedrag:**
Side menu sluit automatisch

**Geconstateerde gedrag:**
Side menu blijft open

**Release:**
v0.8.0

**De melder:** 
Remy Nijsten

**Datum:**
27-01-2022

**Comment by RickLugtigheid** [comment]
Gefikst in pull request: #71
