### ISSUE TITLE
Timer opent opnieuw in nieuwe sessie

### ISSUE THREAD

**Issue by Remynijsten** [Remynijsten/scrumbers-client#75]
**Reproduceren:**
Maak een nieuwe sessie en zet de coffee timer even op 100
Zodra je in de sessie ben kies je de coffee kaart en klik je door tot de timer popup komt
Leave de sessie en maak gelijk een nieuwe aan

**Verwachte gedrag:**
Je kan gewoon opnieuw beginnen met de sessie

**Geconstateerde gedrag:**
De coffee timer van de vorige sessie word gelijk geactiveerd

**Release:**
v0.8.0

**De melder:** 
Remy Nijsten

**Datum:**
31-01-2022

**Comment by RickLugtigheid** [comment]
De bug is gefikst met pull request #77
