### ISSUE TITLE
Je kan opnieuw een sessie joinen die geen spelers meer bevat

### ISSUE THREAD

**Issue by Remynijsten** [Remynijsten/scrumbers-client#76]
Reproduceren:
Maak een sessie aan, join deze en kopieer de url
Leave nu de sessie door een andere pagina te bezoeken
Join opnieuw de sessie die je ge-leaved bent

Verwachte gedrag:
Een 404 omdat de sessie niet meer bestaat

Geconstateerde gedrag:
Je kan opnieuw de sessie joinen

Release:
v0.8.0

De melder: 
Remy Nijsten

Datum:
01-02-2022

**Comment by RickLugtigheid** [comment]
De bug is gefikst met pull request #77
